title: Aadiv Shah
logo: /assets/img/profile.jpeg
email:
description:
favicon: true
color-scheme: light
hide_project_page: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/aadiv1999
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/aadiv-shah-6024/

navigation:
  - name: Home
    link: ./index.html
  - name: Projects
    link: ./pages/projects.html
  - name: Achievements
    link: ./pages/achievements.html
  - name: Blog
    link: ./pages/blog.html
