title: Aadiv Shah
logo: /assets/img/profile.jpeg
email:
description:
favicon: true
color-scheme: light
hide_project_page: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/aadiv1999
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/aadiv-shah-6024/

# Navigation links
navigation:
  - name: Home
    link: ./pages/index/
  - name: Projects
    link: ./pages/projects/
  - name: Achievements
    link: ./pages/achievements/
  - name: Blog
    link: ./pages/blog/

# Permalinks
permalinks:
  pretty: true  # Or specify a custom permalink format if needed
